# Generated by Django 4.2.1 on 2023-05-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='投稿日'),
        ),
    ]
