# Generated by Django 4.2.1 on 2023-05-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(verbose_name='投稿日'),
        ),
    ]
