# Generated by Django 4.2.1 on 2023-05-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_remove_post_time_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='タグ名')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='insta.tag'),
        ),
    ]
