# Generated by Django 4.2.1 on 2023-05-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_chat_created_at_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
    ]
