# Generated by Django 4.2.1 on 2023-05-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_dmchat'),
        ('accounts', '0002_customuser_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='like',
            field=models.ManyToManyField(blank=True, to='insta.post'),
        ),
    ]
