# Generated by Django 4.2.1 on 2023-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_dmchat'),
        ('accounts', '0003_customuser_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark_user', to='insta.post'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_user', to='insta.post'),
        ),
    ]
